apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::980637429038:role/Team2-eks-cluster1-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::980637429038:user/access-key-user
      username: access-key-user
      groups:
        - system:masters

    - userarn: arn:aws:iam::980637429038:user/venkatramana.buthannagari@socgen.com
      username: venkatramana.buthannagari@socgen.com
      groups:
        - system:masters

    - userarn: arn:aws:iam::980637429038:user/kohila.jeyabal@socgen.com
      username: kohila.jeyabal@socgen.com
      groups:
        - system:masters

    - userarn: arn:aws:iam::980637429038:user/gaurav.c.kumar@socgen.com
      username: gaurav.c.kumar@socgen.com
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::980637429038:role/Team2-eks-cluster1-node-group-role\n  groups:\n  - system:bootstrappers\n  - system:nodes\n  username: system:node:{{EC2PrivateDNSName}}    \n","mapUsers":"|\n- rolearn: arn:aws:iam::980637429038:user/access-key-user\n  username: access-key-user  groups:\n  - system:masters\n- userarn: arn:aws:iam::980637429038:user/venkatramana.buthannagari@socgen.com\n  username: venkatramana.buthannagari@socgen.com\n groups:\n  - system:masters \n- userarn: arn:aws:iam::980637429038:user/kohila.jeyabal@socgen.com\n  username: kohila.jeyabal@socgen.com\n groups:\n  - system:masters\n- userarn: arn:aws:iam::980637429038:user/gaurav.c.kumar@socgen.com\n  username: gaurav.c.kumar@socgen.com\n groups:\n  - system:masters"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-04-09T09:32:37Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"218808","uid":"64d21f78-38d5-4a2b-b9ae-8d975ad35228"}}
  creationTimestamp: "2026-04-09T09:32:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "226793"
  uid: 64d21f78-38d5-4a2b-b9ae-8d975ad35228
